name: 'metadata_poc'
version: '1.0.0'
profile: 'metadata_poc'

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

models:
  metadata_poc:
    staging:
      +schema: stg
      +materialized: table